//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Ano e Mês de Emissão.
        /// </summary>
        public static string AnoMesRequired {
            get {
                return ResourceManager.GetString("AnoMesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Ano.
        /// </summary>
        public static string AnoRequired {
            get {
                return ResourceManager.GetString("AnoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profuzzy : Fluxo de Caixa.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profuzzy Consultoria e Sistemas Ltda..
        /// </summary>
        public static string AppProvider {
            get {
                return ResourceManager.GetString("AppProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Veículo com Ar Condicionado.
        /// </summary>
        public static string ArCondicionadoRequired {
            get {
                return ResourceManager.GetString("ArCondicionadoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Atendimento.
        /// </summary>
        public static string AtendimentoDto {
            get {
                return ResourceManager.GetString("AtendimentoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Bacia Operacional.
        /// </summary>
        public static string BaciaDto {
            get {
                return ResourceManager.GetString("BaciaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Bacia Operacional.
        /// </summary>
        public static string BaciaIdRequired {
            get {
                return ResourceManager.GetString("BaciaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Peso Bruto (ton.).
        /// </summary>
        public static string BrutoRequired {
            get {
                return ResourceManager.GetString("BrutoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Linha de Captação.
        /// </summary>
        public static string CaptacaoRequired {
            get {
                return ResourceManager.GetString("CaptacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Cargo.
        /// </summary>
        public static string CargoDto {
            get {
                return ResourceManager.GetString("CargoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Cargo.
        /// </summary>
        public static string CargoIdRequired {
            get {
                return ResourceManager.GetString("CargoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Categoria.
        /// </summary>
        public static string CategoriaIdRequired {
            get {
                return ResourceManager.GetString("CategoriaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Centro de Custos.
        /// </summary>
        public static string CentroDto {
            get {
                return ResourceManager.GetString("CentroDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Número do Chassi.
        /// </summary>
        public static string ChassiNoRequired {
            get {
                return ResourceManager.GetString("ChassiNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Chave.
        /// </summary>
        public static string ChaveNfeRequired {
            get {
                return ResourceManager.GetString("ChaveNfeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Classe.
        /// </summary>
        public static string ClasseIdRequired {
            get {
                return ResourceManager.GetString("ClasseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Classificação.
        /// </summary>
        public static string ClassificacaoIdRequired {
            get {
                return ResourceManager.GetString("ClassificacaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Classificação.
        /// </summary>
        public static string ClassificacaoRequired {
            get {
                return ResourceManager.GetString("ClassificacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CNPJ.
        /// </summary>
        public static string CnpjRequired {
            get {
                return ResourceManager.GetString("CnpjRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Código.
        /// </summary>
        public static string CodigoRequired {
            get {
                return ResourceManager.GetString("CodigoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Coeficiente.
        /// </summary>
        public static string CoeficienteRequired {
            get {
                return ResourceManager.GetString("CoeficienteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ComArRequired {
            get {
                return ResourceManager.GetString("ComArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Tipo de Combustível.
        /// </summary>
        public static string CombustivelIdRequired {
            get {
                return ResourceManager.GetString("CombustivelIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Condição do Veículo.
        /// </summary>
        public static string CondicaoIdRequired {
            get {
                return ResourceManager.GetString("CondicaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se o Veículo tem VIN (chassi) remarcado.
        /// </summary>
        public static string CondicaoVinRequired {
            get {
                return ResourceManager.GetString("CondicaoVinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Consórcio.
        /// </summary>
        public static string ConsorcioDto {
            get {
                return ResourceManager.GetString("ConsorcioDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Consórcio.
        /// </summary>
        public static string ConsorcioIdRequired {
            get {
                return ResourceManager.GetString("ConsorcioIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Conta.
        /// </summary>
        public static string ContaDto {
            get {
                return ResourceManager.GetString("ContaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Conta.
        /// </summary>
        public static string ContaIdRequired {
            get {
                return ResourceManager.GetString("ContaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Contato da Empresa.
        /// </summary>
        public static string ContatoDto {
            get {
                return ResourceManager.GetString("ContatoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Cor conforme Tabela Denatran.
        /// </summary>
        public static string CorDenatranRequired {
            get {
                return ResourceManager.GetString("CorDenatranRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Cor.
        /// </summary>
        public static string CorRequired {
            get {
                return ResourceManager.GetString("CorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Custo da Carroceria.
        /// </summary>
        public static string CstCarroceriaDto {
            get {
                return ResourceManager.GetString("CstCarroceriaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Custo do Chassi.
        /// </summary>
        public static string CstChassiDto {
            get {
                return ResourceManager.GetString("CstChassiDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Custo dos Combustíveis.
        /// </summary>
        public static string CstCombustivelDto {
            get {
                return ResourceManager.GetString("CstCombustivelDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Custo dos Pneus.
        /// </summary>
        public static string CstPneuDto {
            get {
                return ResourceManager.GetString("CstPneuDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Demanda Mensal Transportada.
        /// </summary>
        public static string DemandaRequired {
            get {
                return ResourceManager.GetString("DemandaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Denominação.
        /// </summary>
        public static string DenominacaoRequired {
            get {
                return ResourceManager.GetString("DenominacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Departamento.
        /// </summary>
        public static string DepartamentoDto {
            get {
                return ResourceManager.GetString("DepartamentoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Departamento.
        /// </summary>
        public static string DepartamentoIdRequired {
            get {
                return ResourceManager.GetString("DepartamentoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Descrição.
        /// </summary>
        public static string DescricaoRequired {
            get {
                return ResourceManager.GetString("DescricaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Dia de Operação.
        /// </summary>
        public static string DiaIdRequired {
            get {
                return ResourceManager.GetString("DiaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Dígito Verificador da Chave.
        /// </summary>
        public static string DigitoRequired {
            get {
                return ResourceManager.GetString("DigitoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Linha de Distribuição.
        /// </summary>
        public static string DistribuicaoRequired {
            get {
                return ResourceManager.GetString("DistribuicaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Operação aos Domingos.
        /// </summary>
        public static string DomingosRequired {
            get {
                return ResourceManager.GetString("DomingosRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Jurisdição.
        /// </summary>
        public static string DominioIdRequired {
            get {
                return ResourceManager.GetString("DominioIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to das Empresa no Consórcio.
        /// </summary>
        public static string EConsorcioDto {
            get {
                return ResourceManager.GetString("EConsorcioDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Veículo da Empresa.
        /// </summary>
        public static string ECVeiculoDto {
            get {
                return ResourceManager.GetString("ECVeiculoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade de Eixos Dianteiros.
        /// </summary>
        public static string EixoFrenteRequired {
            get {
                return ResourceManager.GetString("EixoFrenteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade de Eixos Traseiros.
        /// </summary>
        public static string EixoTrasRequired {
            get {
                return ResourceManager.GetString("EixoTrasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Tecnologia Embarcada.
        /// </summary>
        public static string EmbarcadoDto {
            get {
                return ResourceManager.GetString("EmbarcadoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data de Emissão.
        /// </summary>
        public static string EmissaoRequired {
            get {
                return ResourceManager.GetString("EmissaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Emitente.
        /// </summary>
        public static string EmitenteRequired {
            get {
                return ResourceManager.GetString("EmitenteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Empresa.
        /// </summary>
        public static string EmpresaDto {
            get {
                return ResourceManager.GetString("EmpresaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Empresa.
        /// </summary>
        public static string EmpresaIdRequired {
            get {
                return ResourceManager.GetString("EmpresaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Encargo Social.
        /// </summary>
        public static string EncargoDto {
            get {
                return ResourceManager.GetString("EncargoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Encargo Social.
        /// </summary>
        public static string EncargoIdRequired {
            get {
                return ResourceManager.GetString("EncargoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Endereço ou Localização.
        /// </summary>
        public static string EnderecoRequired {
            get {
                return ResourceManager.GetString("EnderecoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Equipamento (Item).
        /// </summary>
        public static string EquipamentoIdRequired {
            get {
                return ResourceManager.GetString("EquipamentoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Demanda Mensal Equivalente.
        /// </summary>
        public static string EquivalenteRequired {
            get {
                return ResourceManager.GetString("EquivalenteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Escapamento Horizontal.
        /// </summary>
        public static string EscapeHRequired {
            get {
                return ResourceManager.GetString("EscapeHRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Escapamento Vertical.
        /// </summary>
        public static string EscapeVRequired {
            get {
                return ResourceManager.GetString("EscapeVRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Faixa Etária.
        /// </summary>
        public static string EtariaIdRequired {
            get {
                return ResourceManager.GetString("EtariaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Espécie de Veículo.
        /// </summary>
        public static string EVeiculoIdRequired {
            get {
                return ResourceManager.GetString("EVeiculoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nome Fantasia.
        /// </summary>
        public static string FantasiaRequired {
            get {
                return ResourceManager.GetString("FantasiaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Finalidade.
        /// </summary>
        public static string FinalidadeRequired {
            get {
                return ResourceManager.GetString("FinalidadeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Fornecedor.
        /// </summary>
        public static string FornecedorDto {
            get {
                return ResourceManager.GetString("FornecedorDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Fornecedor.
        /// </summary>
        public static string FornecedorIdRequired {
            get {
                return ResourceManager.GetString("FornecedorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Forma de Pagamento.
        /// </summary>
        public static string FPagamentoIdRequired {
            get {
                return ResourceManager.GetString("FPagamentoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Frota da Empresa.
        /// </summary>
        public static string FrotaDto {
            get {
                return ResourceManager.GetString("FrotaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Distribuição Horária da Frota.
        /// </summary>
        public static string FrotaHoraDto {
            get {
                return ResourceManager.GetString("FrotaHoraDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Frota Operacional.
        /// </summary>
        public static string FrotaOperacaoRequired {
            get {
                return ResourceManager.GetString("FrotaOperacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Quantidade de Veículos.
        /// </summary>
        public static string FrotaRequired {
            get {
                return ResourceManager.GetString("FrotaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.U. (Fator de Uso) por Função.
        /// </summary>
        public static string FuFuncaoDto {
            get {
                return ResourceManager.GetString("FuFuncaoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Função.
        /// </summary>
        public static string FuncaoDto {
            get {
                return ResourceManager.GetString("FuncaoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Função.
        /// </summary>
        public static string FuncaoIdRequired {
            get {
                return ResourceManager.GetString("FuncaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Gratuidade.
        /// </summary>
        public static string GratuidadeRequired {
            get {
                return ResourceManager.GetString("GratuidadeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Grupo.
        /// </summary>
        public static string GrupoRequired {
            get {
                return ResourceManager.GetString("GrupoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Código Gtin.
        /// </summary>
        public static string GtinRequired {
            get {
                return ResourceManager.GetString("GtinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Faixa Horária.
        /// </summary>
        public static string HorarioIdRequired {
            get {
                return ResourceManager.GetString("HorarioIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Idade Média da Frota.
        /// </summary>
        public static string IdadeFrotaRequired {
            get {
                return ResourceManager.GetString("IdadeFrotaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Veículo Inativo.
        /// </summary>
        public static string InativoRequired {
            get {
                return ResourceManager.GetString("InativoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Hora de Início.
        /// </summary>
        public static string InicioRequired {
            get {
                return ResourceManager.GetString("InicioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Instalação da Empresa.
        /// </summary>
        public static string InstalacaoDto {
            get {
                return ResourceManager.GetString("InstalacaoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Instalação.
        /// </summary>
        public static string InstalacaoIdRequired {
            get {
                return ResourceManager.GetString("InstalacaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data de Integração.
        /// </summary>
        public static string IntegracaoRequired {
            get {
                return ResourceManager.GetString("IntegracaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número do Item.
        /// </summary>
        public static string ItemIdRequired {
            get {
                return ResourceManager.GetString("ItemIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Item.
        /// </summary>
        public static string ItemRequired {
            get {
                return ResourceManager.GetString("ItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Quilometragem Produtiva.
        /// </summary>
        public static string KmProdutivoRequired {
            get {
                return ResourceManager.GetString("KmProdutivoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Linha.
        /// </summary>
        public static string LinhaDto {
            get {
                return ResourceManager.GetString("LinhaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Linha.
        /// </summary>
        public static string LinhaIdRequired {
            get {
                return ResourceManager.GetString("LinhaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Peso Líquido (ton.).
        /// </summary>
        public static string LiquidoRequired {
            get {
                return ResourceManager.GetString("LiquidoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade máxima de passageiros sentados.
        /// </summary>
        public static string LotacaoRequired {
            get {
                return ResourceManager.GetString("LotacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Lote.
        /// </summary>
        public static string LoteDto {
            get {
                return ResourceManager.GetString("LoteDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Marca.
        /// </summary>
        public static string MarcaRequired {
            get {
                return ResourceManager.GetString("MarcaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Mês.
        /// </summary>
        public static string MesRequired {
            get {
                return ResourceManager.GetString("MesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Modelo.
        /// </summary>
        public static string ModeloRequired {
            get {
                return ResourceManager.GetString("ModeloRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Município.
        /// </summary>
        public static string MunicipioIdRequired {
            get {
                return ResourceManager.GetString("MunicipioIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Município.
        /// </summary>
        public static string MunicipioRequired {
            get {
                return ResourceManager.GetString("MunicipioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Natureza da Operação.
        /// </summary>
        public static string NaturezaRequired {
            get {
                return ResourceManager.GetString("NaturezaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Código NCM.
        /// </summary>
        public static string NcmIdRequired {
            get {
                return ResourceManager.GetString("NcmIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Local de Entrega.
        /// </summary>
        public static string NfEntregaDto {
            get {
                return ResourceManager.GetString("NfEntregaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da NF-e (Nota Fiscal Eletrônica).
        /// </summary>
        public static string NFiscalDto {
            get {
                return ResourceManager.GetString("NFiscalDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Nota Fiscal Referenciada.
        /// </summary>
        public static string NfReferenciaDto {
            get {
                return ResourceManager.GetString("NfReferenciaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Aquisição de Veículos.
        /// </summary>
        public static string NfVeiculoDto {
            get {
                return ResourceManager.GetString("NfVeiculoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nome.
        /// </summary>
        public static string NomeRequired {
            get {
                return ResourceManager.GetString("NomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Nota Fiscal.
        /// </summary>
        public static string NotaIdRequired {
            get {
                return ResourceManager.GetString("NotaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Número.
        /// </summary>
        public static string NumeroRequired {
            get {
                return ResourceManager.GetString("NumeroRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Operação.
        /// </summary>
        public static string OperacaoIdRequired {
            get {
                return ResourceManager.GetString("OperacaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Tipo de Operação.
        /// </summary>
        public static string OperacaoRequired {
            get {
                return ResourceManager.GetString("OperacaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o País.
        /// </summary>
        public static string PaisIdRequired {
            get {
                return ResourceManager.GetString("PaisIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Quantidade de Passageiros por m².
        /// </summary>
        public static string Passageirom2Required {
            get {
                return ResourceManager.GetString("Passageirom2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Quantidade de Passageiros.
        /// </summary>
        public static string PassageirosRequired {
            get {
                return ResourceManager.GetString("PassageirosRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dos Parâmetros de Consumo.
        /// </summary>
        public static string PCoeficienteDto {
            get {
                return ResourceManager.GetString("PCoeficienteDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dos Coeficientes de Consumo de Combustíveis.
        /// </summary>
        public static string PCombustivelDto {
            get {
                return ResourceManager.GetString("PCombustivelDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Placa.
        /// </summary>
        public static string PlacaRequired {
            get {
                return ResourceManager.GetString("PlacaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Localização da(s) Porta(s) de Entrada.
        /// </summary>
        public static string PortaInRequired {
            get {
                return ResourceManager.GetString("PortaInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade de Portas.
        /// </summary>
        public static string PortasRequired {
            get {
                return ResourceManager.GetString("PortasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Prefixo ou Número.
        /// </summary>
        public static string PrefixoRequired {
            get {
                return ResourceManager.GetString("PrefixoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to das Premissas para Composição de Custos e Receitas.
        /// </summary>
        public static string PremissaDto {
            get {
                return ResourceManager.GetString("PremissaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Produto.
        /// </summary>
        public static string ProdutoDto {
            get {
                return ResourceManager.GetString("ProdutoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Finalidade (Propósito).
        /// </summary>
        public static string PropositoIdRequired {
            get {
                return ResourceManager.GetString("PropositoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Quantidade.
        /// </summary>
        public static string QuantidadeRequired {
            get {
                return ResourceManager.GetString("QuantidadeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a participação (%).
        /// </summary>
        public static string RatioRequired {
            get {
                return ResourceManager.GetString("RatioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Razão Social.
        /// </summary>
        public static string RazaoRequired {
            get {
                return ResourceManager.GetString("RazaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data de Referência.
        /// </summary>
        public static string ReferenciaRequired {
            get {
                return ResourceManager.GetString("ReferenciaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Renavam.
        /// </summary>
        public static string RenavamRequired {
            get {
                return ResourceManager.GetString("RenavamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Restrições.
        /// </summary>
        public static string RestricaoIdRequired {
            get {
                return ResourceManager.GetString("RestricaoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Operação aos Sábados.
        /// </summary>
        public static string SabadosRequired {
            get {
                return ResourceManager.GetString("SabadosRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Saída(s) Dianteira(s).
        /// </summary>
        public static string SaidaFrenteRequired {
            get {
                return ResourceManager.GetString("SaidaFrenteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Saída(s) Central(is).
        /// </summary>
        public static string SaidaMeioRequired {
            get {
                return ResourceManager.GetString("SaidaMeioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Saída(s) Traseira(s).
        /// </summary>
        public static string SaidaTrasRequired {
            get {
                return ResourceManager.GetString("SaidaTrasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dos Salários.
        /// </summary>
        public static string SalarioDto {
            get {
                return ResourceManager.GetString("SalarioDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Valor do Salário Base.
        /// </summary>
        public static string SalBaseRequired {
            get {
                return ResourceManager.GetString("SalBaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Sentido.
        /// </summary>
        public static string SentidoRequired {
            get {
                return ResourceManager.GetString("SentidoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Série.
        /// </summary>
        public static string SerieRequired {
            get {
                return ResourceManager.GetString("SerieRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Setor.
        /// </summary>
        public static string SetorDto {
            get {
                return ResourceManager.GetString("SetorDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Setor.
        /// </summary>
        public static string SetorIdRequired {
            get {
                return ResourceManager.GetString("SetorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Sistema.
        /// </summary>
        public static string SistemaDto {
            get {
                return ResourceManager.GetString("SistemaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Sistema.
        /// </summary>
        public static string SistemaIdRequired {
            get {
                return ResourceManager.GetString("SistemaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Tarifa.
        /// </summary>
        public static string TarifaDto {
            get {
                return ResourceManager.GetString("TarifaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Modalidade Tarifária.
        /// </summary>
        public static string TarifariaIdRequired {
            get {
                return ResourceManager.GetString("TarifariaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da Modalidade Tarifária.
        /// </summary>
        public static string TCategoriaDto {
            get {
                return ResourceManager.GetString("TCategoriaDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o(s) Telefone(s).
        /// </summary>
        public static string TelefoneRequired {
            get {
                return ResourceManager.GetString("TelefoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a quantidade de Titulares na Função.
        /// </summary>
        public static string TitularRequired {
            get {
                return ResourceManager.GetString("TitularRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Título.
        /// </summary>
        public static string TituloRequired {
            get {
                return ResourceManager.GetString("TituloRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Capacidade Máxima de Tração (ton.).
        /// </summary>
        public static string TracaoRequired {
            get {
                return ResourceManager.GetString("TracaoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se Linha de Transporte.
        /// </summary>
        public static string TransporteRequired {
            get {
                return ResourceManager.GetString("TransporteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Turno.
        /// </summary>
        public static string TurnoDto {
            get {
                return ResourceManager.GetString("TurnoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Tipo de Veículo.
        /// </summary>
        public static string TVeiculoIdRequired {
            get {
                return ResourceManager.GetString("TVeiculoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a U.F..
        /// </summary>
        public static string UfIdRequired {
            get {
                return ResourceManager.GetString("UfIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Unidade Comercial.
        /// </summary>
        public static string UnidadeIdRequired {
            get {
                return ResourceManager.GetString("UnidadeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Custo Unitário R$.
        /// </summary>
        public static string UnitarioRequired {
            get {
                return ResourceManager.GetString("UnitarioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Custo Unitário R$ do Pneu.
        /// </summary>
        public static string UnitPneuRequired {
            get {
                return ResourceManager.GetString("UnitPneuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Custo Unitário R$ da Recapagem.
        /// </summary>
        public static string UnitRecapRequired {
            get {
                return ResourceManager.GetString("UnitRecapRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe se há Operação em Dias Úteis.
        /// </summary>
        public static string UteisRequired {
            get {
                return ResourceManager.GetString("UteisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Valor Base R$.
        /// </summary>
        public static string ValorBaseRequired {
            get {
                return ResourceManager.GetString("ValorBaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Valor R$.
        /// </summary>
        public static string ValorRequired {
            get {
                return ResourceManager.GetString("ValorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Catálogo de Veículos.
        /// </summary>
        public static string VCatalogoDto {
            get {
                return ResourceManager.GetString("VCatalogoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Veículo.
        /// </summary>
        public static string VeiculoDto {
            get {
                return ResourceManager.GetString("VeiculoDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Veículo.
        /// </summary>
        public static string VeiculoIdRequired {
            get {
                return ResourceManager.GetString("VeiculoIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Equipamento do Veículo.
        /// </summary>
        public static string VEquipamentoDto {
            get {
                return ResourceManager.GetString("VEquipamentoDto", resourceCulture);
            }
        }
    }
}
